### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by grasses** [starlightme/a-simple-script-for-v2ex-sign#1]
[root@/]# python v2ex.py
Traceback (most recent call last):
  File "v2ex.py", line 37, in <module>
    main()
  File "v2ex.py", line 31, in main
    once2 = re.search(r'/mission/daily/redeem\?once=[0-9]+',page2).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by starlightme** [comment]
I advise you to remove all comments in this  code and insure requests modules had been installed. The script works well on my vps(Python 2.7.3).
The possible reason to explain this situation is that  you've already sign up today.

**Comment by grasses** [comment]
thx
